version: '3.9'

services:
  postgres:
    image: postgres:15.6
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: cypher_user
      POSTGRES_PASSWORD: cypher_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/Users/dashingsat/data
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local


