version: "3.9"
services:
  db:
    image: "postgres:15.3"
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_pass
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  zk:
    image: "zookeeper:3.5.6"

    ports:
      - 2181:2181